services:
  db:
    container_name: mysqlfpeos
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3308:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-php-frankenphp
    container_name: phpfpeos
    ports:
      - "8000:80"
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://symfony:symfony@db:3306/eos_db_test?serverVersion=8.0
      SERVER_NAME: localhost, php:80
    volumes:
      - .:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test_network

networks:
  test_network:
    driver: bridge