services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Autorise un mot de passe vide pour le root
      MYSQL_DATABASE: eos_db_test
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
  php:
    image: dunglas/frankenphp
    environment:
      APP_ENV: test
    env_file:
      - .env.test
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        install-php-extensions pdo_mysql xdebug &&
        echo 'xdebug.mode=coverage' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
        php -S 0.0.0.0:80 -t public
      "
    depends_on:
      db

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
