networks:
  test_network:
    driver: bridge

services:
  db:
    container_name: mysqlfpeos
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    command: >
      sh -c "
        install-php-extensions pdo_mysql xdebug &&
        php -m | grep pdo_mysql &&  # Vérifie que l'extension est bien installée
        echo 'xdebug.mode=coverage' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
        php -S 0.0.0.0:80 -t public
      "
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3308:3306"
    networks:
      - test_network

  php:
    image: dunglas/frankenphp
    environment:
      APP_ENV: test
    env_file:
      - .env.test
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        install-php-extensions pdo_mysql xdebug &&
        echo 'xdebug.mode=coverage' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
        php -S 0.0.0.0:80 -t public
      "
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test_network

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "8025:8025"
    networks:
      - test_network
