networks:
  test_network:
    driver: bridge

services:
  php:
    image: dunglas/frankenphp
    environment:
      APP_ENV: test
    env_file:
      - .env.test
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        install-php-extensions pdo_mysql xdebug &&
        echo 'xdebug.mode=coverage' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
        php -S 0.0.0.0:80 -t public
      "
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret # Définit le mot de passe pour root
      MYSQL_DATABASE: eos_db_test # Crée automatiquement la base eos_db_test
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=secret"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - '3306:3306'
    networks:
      - test_network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8899:80"
    networks:
      - test_network

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "8025:8025"
    networks:
      - test_network
