services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenphp_dev
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://symfony:symfony@db:3306/eos_db_test?serverVersion=8.0
    volumes:
      - .:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
    working_dir: /app
    healthcheck:
      test: ["CMD-SHELL", "mysql -h db -u symfony -psymfony eos_db_test -e 'SELECT 1;'"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "symfony", "--password=symfony"]
      interval: 5s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'