services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://symfony:symfony@db:3306/eos_db_test?serverVersion=8.0
    env_file:
      - .env.test
    volumes:
      - .:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 5s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'