services:
  db:
    container_name: mysqlfpeos
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3308:3306'
    volumes:
      - ./frankenphp/mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-php-frankenphp
    container_name: phpfpeos
    restart: unless-stopped
    ports:
      - "8000:80"
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    environment:
      DATABASE_URL: mysql://symfony:symfony@db:3306/eos_db?serverVersion=8.0
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      # Mercure configuration pour FrankenPHP intégré
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_JWT_SECRET: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_URL: http://mercure/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:3000/.well-known/mercure
      # Extra configuration
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins *
        publish_origins *
        subscribe_origins *
        topics auction/*
        subscriptions
        demo
        heartbeat 40s
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      db:
        condition: service_healthy
      mercure:
        condition: service_started
    networks:
      - app_network

  mercure:
    container_name: mereos
    image: dunglas/mercure
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      SERVER_NAME: ":80"
      PUBLISH_ALLOWED_ORIGINS: '*'  # Changez pour '*' en développement
      DEBUG: '1'
      CORS_ALLOWED_ORIGINS: '*'  # Permet toutes les origines en dev
      ALLOW_ANONYMOUS: '1'
      MERCURE_EXTRA_DIRECTIVES: |
        debug
        cors_origins *
        anonymous
        subscriptions
        heartbeat 40s
        demo
    ports:
      - '3000:80'
    depends_on:
      - db
    networks:
      - app_network

  phpmyadmin:
    container_name: phpmyfpeos
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
      UPLOAD_LIMIT: 20M
    ports:
      - '8899:80'
    depends_on:
      - db
    networks:
      - app_network

  mailhog:
    container_name: mailhogfpeos
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app_network

volumes:
  caddy_data:
  caddy_config:

networks:
  app_network:
    driver: bridge