networks:
  test_network:
    driver: bridge

services:
  db:
    container_name: mysqlfpeos
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_HOST: '%'  # Permet les connexions de n'importe où
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3308:3306"
    networks:
      - test_network

  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenphp_test
    container_name: phpfpeos
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://symfony:symfony@db:3306/eos_db?serverVersion=8.0
      XDEBUG_MODE: coverage
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - test_network

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "8025:8025"
    networks:
      - test_network