services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenphp_dev
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://symfony:symfony@db:3306/eos_db_test?serverVersion=8.0
    volumes:
      - .:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
    working_dir: /app
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 1s
      timeout: 5s
      retries: 10

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'