services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenphp_dev
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://symfony:symfony@db:3306/eos_db_test?serverVersion=8.0
    volumes:
      - .:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
    working_dir: /app
    depends_on:
      db:
        condition: service_started

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Accélère l'initialisation
    command: --default-authentication-plugin=mysql_native_password  # Plus rapide que sha2
    healthcheck:
      test: ["CMD-SHELL", "mysql -u symfony -psymfony -e 'SELECT 1' eos_db_test"]
      interval: 1s
      timeout: 2s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'