services:
  php:
    image: dunglas/frankenphp
    environment:
      APP_ENV: test
    env_file:
      - .env.test
    volumes:
      - .:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
    working_dir: /app
    command: >
      sh -c "
        install-php-extensions pdo_mysql xdebug &&
        echo 'xdebug.mode=coverage' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini &&
        frankenphp run --config /etc/caddy/Caddyfile
      "
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db_test
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    depends_on:
      db:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
