services:
  php:
    image: dunglas/frankenphp
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://symfony:symfony@db:3306/eos_db_test?serverVersion=8.0
    volumes:
      - .:/app:rw
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    command: php -S 0.0.0.0:80 -t public
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eos_db_test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'