# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mercure_jwt_secret: '%env(MERCURE_JWT_SECRET)%'
    uploads_directory: '%kernel.project_dir%/public/uploads/'
    auctions_directory: '%kernel.project_dir%/public/uploads/auctions'
    products_directory: '%kernel.project_dir%/public/uploads/products'
    jwt_secret: '%env(JWT_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:        # Correction: _defaults au lieu de *defaults
        autowire: true
        autoconfigure: true
    # Configure AuctionController avec toutes ses dépendances
    App\Controller\AuctionController:
        arguments:
            $auctionRepository: '@App\Repository\AuctionRepository'
            $bidRepository: '@App\Repository\BidRepository'
            $professionRepository: '@App\Repository\ProfessionRepository'
            $paginator: '@knp_paginator'
            $logger: '@logger'
            $jwtProvider: '@App\Service\JwtProvider'
            $hub: '@mercure.hub.default'

    App\EventListener\AuctionStatusListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }

    App\Controller\BidController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $auctionRepository: '@App\Repository\AuctionRepository'
            $bidRepository: '@App\Repository\BidRepository'
            $hub: '@mercure.hub.default'
            $logger: '@logger'

    # Register all services from src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\EmailService:
        arguments:
            $contactEmail: '%env(CONTACT_EMAIL)%'
